### ISSUE TITLE
Application generated with gradle support is unavailable on port 8080

### ISSUE THREAD

**Issue by ExAnimoso** [sunrise-r/jhipster-quarkus#13]
**Describe the bug**
Application is unavailable on port 8080 after creating application with gradle support.

**To Reproduce**
1. Create new directory and cd into it.
2. Use jhipster --blueprints quarkus to generate application.
3. Skip through settings steps and select gradle for building the backend.
4. Launch the application ./gradlew
5. Go to localhost:8080 and observe HTTP 404 error with no home page displayed.

**Expected behavior**
Expected to see jhipster home page by opening localhost:8080.

**Comment by inngvar** [comment]
fixed
